
make testing:
	c++ ising_testing.cpp ising_model.cpp -o testing -O2 -I /home/johan/armadillo-9.900.2/include -DARMA_DONT_USE_WRAPPER -lblas -llapack

make op:
	c++ ising_testing.cpp ising_model.cpp -o testing -O3 -I /home/Documents/armadillo-9.900.3/include -DARMA_DONT_USE_WRAPPER -lblas -llapack
