
make 2spin:
	c++ ising_2_spins.cpp ising_model.cpp -o spins2 -O3 -I /home/johan/armadillo-9.900.2/include -DARMA_DONT_USE_WRAPPER -lblas -llapack

make 2spinnmc:
	c++ ising_2_spins_mc.cpp ising_model.cpp -o spins2_mc -O3 -I /home/johan/armadillo-9.900.2/include -DARMA_DONT_USE_WRAPPER -lblas -llapack

make pde:
	c++ ising_2_spins_mc.cpp ising_model.cpp -o spins2_mc -O3 -I /home/johan/armadillo-9.900.2/include -DARMA_DONT_USE_WRAPPER -lblas -llapack
