

jacobi:
	g++ main.cpp jacobi_rotation.cpp -o main.out
	
arma:
	g++ armadillo_implementation.cpp -o arma.out -O2 -I /home/johan/armadillo/armadillo-9.900.2/include -DARMA_DONT_USE_WRAPPER -lblas -llapack
