

5c:
	c++ p5c.cpp algorithms.cpp -o p5c -O3 -I /home/johan/armadillo-9.900.2/include -DARMA_DONT_USE_WRAPPER -lblas -llapack


5f:
	c++ p5f.cpp algorithms.cpp -o p5f -O3 -I /home/johan/armadillo-9.900.2/include -DARMA_DONT_USE_WRAPPER -lblas -llapack

lithos:
	c++ litho.cpp algorithms.cpp -o litho -O3 -I /home/johan/armadillo-9.900.2/include -DARMA_DONT_USE_WRAPPER -lblas -llapack
